-- Baseline schema for the library application.
--
-- This migration reproduces exactly the schema Hibernate generated from the entity
-- model (verified by exporting jakarta.persistence.schema-generation.scripts), so it
-- is a faithful starting point rather than an approximation. From here on, every
-- schema change MUST be a new V<n>__*.sql file instead of editing entities alone.
--
-- Notes:
--  * The project uses Hibernate Envers (@Audited), hence the *_aud tables and revinfo.
--  * Column types are chosen to be valid on both H2 (current runtime) and MySQL.

CREATE TABLE revinfo (
    rev     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    revtstmp BIGINT,
    PRIMARY KEY (rev)
);

CREATE TABLE books (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title                  VARCHAR(255),
    author                 VARCHAR(255),
    translator             VARCHAR(255),
    publisher              VARCHAR(255),
    isbn10                 VARCHAR(255),
    isbn13                 VARCHAR(255),
    description            VARCHAR(2000),
    dewey_decimal          VARCHAR(255),
    congress_classification VARCHAR(255),
    subject                VARCHAR(255),
    summary                VARCHAR(2000),
    publication_date       DATE,
    page_count             INTEGER,
    language               VARCHAR(255),
    book_cover_file        BLOB,
    edition                VARCHAR(255),
    copy_count             INTEGER,
    library_section        VARCHAR(255),
    shelf_code             VARCHAR(255),
    row_numbers            VARCHAR(255),
    column_number          VARCHAR(255),
    position_note          VARCHAR(2000),
    active                 BOOLEAN,
    PRIMARY KEY (id)
);

CREATE TABLE person (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    email           VARCHAR(255) NOT NULL,
    national_id     VARCHAR(255) NOT NULL,
    phone           VARCHAR(255),
    birth_date      DATE,
    membership_date DATE,
    membership_type VARCHAR(255),
    address         VARCHAR(255),
    notes           VARCHAR(2000),
    profile_picture BLOB,
    active          BOOLEAN,
    PRIMARY KEY (id),
    CONSTRAINT uk_person_email UNIQUE (email),
    CONSTRAINT uk_person_national_id UNIQUE (national_id)
);

CREATE TABLE book_loans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    person_id   BIGINT NOT NULL,
    book_id     BIGINT NOT NULL,
    loan_date   DATE NOT NULL,
    due_date    DATE NOT NULL,
    return_date DATE,
    status      VARCHAR(20) NOT NULL,
    notes       VARCHAR(1000),
    PRIMARY KEY (id),
    CONSTRAINT fk_book_loans_book   FOREIGN KEY (book_id)   REFERENCES books (id),
    CONSTRAINT fk_book_loans_person FOREIGN KEY (person_id) REFERENCES person (id)
);

CREATE TABLE reservations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    person_id        BIGINT NOT NULL,
    book_id          BIGINT NOT NULL,
    reservation_date DATE,
    expiry_date      DATE,
    status           VARCHAR(20),
    PRIMARY KEY (id),
    CONSTRAINT fk_reservations_book   FOREIGN KEY (book_id)   REFERENCES books (id),
    CONSTRAINT fk_reservations_person FOREIGN KEY (person_id) REFERENCES person (id)
);

CREATE TABLE messages (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sender               VARCHAR(100) NOT NULL,
    sender_farsi_title   VARCHAR(200) NOT NULL,
    recipient            VARCHAR(100),
    recipient_farsi_title VARCHAR(200),
    subject              VARCHAR(200),
    message              VARCHAR(4000) NOT NULL,
    is_active            BOOLEAN,
    parent_message_id    BIGINT,
    data_state           INTEGER,
    create_user          VARCHAR(100),
    create_date          TIMESTAMP(6),
    modify_user          VARCHAR(100),
    modify_date          TIMESTAMP(6),
    delete_user          VARCHAR(100),
    delete_date          TIMESTAMP(6),
    enable_send_sms      BOOLEAN,
    priority             VARCHAR(50),
    national_code        VARCHAR(10),
    recipients           VARCHAR(500),
    message_status       VARCHAR(20),
    PRIMARY KEY (id),
    CONSTRAINT fk_messages_parent FOREIGN KEY (parent_message_id) REFERENCES messages (id)
);

CREATE TABLE file_attachments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_name          VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    content_type       VARCHAR(100) NOT NULL,
    file_size          BIGINT NOT NULL,
    file_path          VARCHAR(500) NOT NULL,
    message_id         BIGINT,
    upload_status      VARCHAR(20),
    create_date        TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_file_attachments_message FOREIGN KEY (message_id) REFERENCES messages (id)
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(100) NOT NULL,
    farsi_title   VARCHAR(200) NOT NULL,
    email         VARCHAR(100),
    phone_number  VARCHAR(15),
    national_code VARCHAR(10),
    is_active     BOOLEAN,
    last_seen     TIMESTAMP(6),
    create_date   TIMESTAMP(6),
    online_status VARCHAR(20),
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username)
);

-- ---------------------------------------------------------------------------
-- Hibernate Envers audit tables
-- ---------------------------------------------------------------------------

CREATE TABLE books_aud (
    id                     BIGINT NOT NULL,
    rev                    INTEGER NOT NULL,
    revtype                TINYINT,
    title                  VARCHAR(255),
    author                 VARCHAR(255),
    translator             VARCHAR(255),
    publisher              VARCHAR(255),
    isbn10                 VARCHAR(255),
    isbn13                 VARCHAR(255),
    description            VARCHAR(2000),
    dewey_decimal          VARCHAR(255),
    congress_classification VARCHAR(255),
    subject                VARCHAR(255),
    summary                VARCHAR(2000),
    publication_date       DATE,
    page_count             INTEGER,
    language               VARCHAR(255),
    book_cover_file        VARBINARY(255),
    edition                VARCHAR(255),
    copy_count             INTEGER,
    library_section        VARCHAR(255),
    shelf_code             VARCHAR(255),
    row_numbers            VARCHAR(255),
    column_number          VARCHAR(255),
    position_note          VARCHAR(2000),
    active                 BOOLEAN,
    PRIMARY KEY (rev, id),
    CONSTRAINT fk_books_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE person_aud (
    id              BIGINT NOT NULL,
    rev             INTEGER NOT NULL,
    revtype         TINYINT,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    email           VARCHAR(255),
    national_id     VARCHAR(255),
    phone           VARCHAR(255),
    birth_date      DATE,
    membership_date DATE,
    membership_type VARCHAR(255),
    address         VARCHAR(255),
    notes           VARCHAR(2000),
    profile_picture VARBINARY(255),
    active          BOOLEAN,
    PRIMARY KEY (rev, id),
    CONSTRAINT fk_person_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE book_loans_aud (
    id          BIGINT NOT NULL,
    rev         INTEGER NOT NULL,
    revtype     TINYINT,
    person_id   BIGINT,
    book_id     BIGINT,
    loan_date   DATE,
    due_date    DATE,
    return_date DATE,
    status      VARCHAR(20),
    notes       VARCHAR(1000),
    PRIMARY KEY (rev, id),
    CONSTRAINT fk_book_loans_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE reservations_aud (
    id               BIGINT NOT NULL,
    rev              INTEGER NOT NULL,
    revtype          TINYINT,
    person_id        BIGINT,
    book_id          BIGINT,
    reservation_date DATE,
    expiry_date      DATE,
    status           VARCHAR(20),
    PRIMARY KEY (rev, id),
    CONSTRAINT fk_reservations_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE messages_aud (
    id                   BIGINT NOT NULL,
    rev                  INTEGER NOT NULL,
    revtype              TINYINT,
    sender               VARCHAR(100),
    sender_farsi_title   VARCHAR(200),
    recipient            VARCHAR(100),
    recipient_farsi_title VARCHAR(200),
    subject              VARCHAR(200),
    message              VARCHAR(4000),
    is_active            BOOLEAN,
    parent_message_id    BIGINT,
    data_state           INTEGER,
    create_user          VARCHAR(100),
    create_date          TIMESTAMP(6),
    modify_user          VARCHAR(100),
    modify_date          TIMESTAMP(6),
    delete_user          VARCHAR(100),
    delete_date          TIMESTAMP(6),
    enable_send_sms      BOOLEAN,
    priority             VARCHAR(50),
    national_code        VARCHAR(10),
    recipients           VARCHAR(500),
    message_status       VARCHAR(20),
    PRIMARY KEY (rev, id),
    CONSTRAINT fk_messages_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
